services:
  txapo_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5228:80"
    networks:
      - faturize_api_network

networks:
  faturize_api_network:
    driver: bridge
      